cd model1_insightface
python3 prepare.py
python3 train.py
cd ../model2_insightface
python3 prepare.py
python3 train.py
cd ../model3_insightface
python3 prepare.py
python3 train.py
cd ../model4_insightface
python3 prepare.py
python3 train.py
cd ../model5_dlib
python3 prepare.py
python3 train.py
cd ../model6_facenet
python3 prepare.py
python3 train.py
cd ../model7_facenet
python3 prepare.py
python3 train.py
cd ../vggface2_resnet50_128
python3 prepare.py
python3 train.py
cd ../vggface2_resnet50_256
python3 prepare.py
python3 train.py
cd ../vggface2_resnet50_ft
python3 prepare.py
python3 train.py
cd ../vggface2_resnet50_scratch
python3 prepare.py
python3 train.py
cd ../vggface2_senet50_128
python3 prepare.py
python3 train.py
cd ../vggface2_senet50_256
python3 prepare.py
python3 train.py
cd ../vggface2_senet50_ft
python3 prepare.py
python3 train.py
cd ../vggface2_senet50_scratch
python3 prepare.py
python3 train.py
cd ../
python3 generate_pseudo.py
